### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by IvanSmiths** [IvanSmiths/cover-letter-builder-pro#5]
- [x] Add language select (optional, by default answer in the cover letter language)
- [x] Add name of recruiter.
- [x] Break the full company address into two rows in the pdf
- [ ] Add just name of recruiter in the salutation
- [ ] Add personal input about experience (or something that the user want to point out, like school) 
- [ ] Add 11y
